### ISSUE TITLE
version of binarysearch in npm

### ISSUE THREAD

**Issue by michAtEl** [soldair/node-binarysearch#11]
Hi,
npm has version 1.0.0 of this library (2016-03-09T13:38:40.052Z). In github, there is version 1.0.1. Will you update binarysearch on npm or should we install binarysearch from github?

Thanks
Michael

**Comment by slawiko** [comment]
@soldair @nlacasse @chrisn @pheyvaer 
You are listed as contributors. Can you take an action on this issue?

**Comment by soldair** [comment]
I mean it looks like it updates examples. so no reason not to =)
