### ISSUE TITLE
returning 1 when should not.

### ISSUE THREAD

**Issue by bryanrasmussen** [soldair/node-binarysearch#6]
this bs(["a","b","cde","f"],"wtf") returns 1. 
this 
bs([1,2,3,4],"wtf");
also returns 1.
obviously the second one is a data type problem, probably should just check to see that it is the same data type coming in and fail if not. 

The first one I suppose is that an array of sorted numerical datatypes are expected, but that seems messed up since binary search can be used with sorted string arrays also.

**Comment by soldair** [comment]
its been a while but i think you need to pass in your own comparator to handle string values/mixed type values.
ill take a look though =)

**Comment by bryanrasmussen** [comment]
hi, you're right of course, but I think there should be some sort of
warning popping up. especially in cases of type mismatch.


I did get it working with my own comparator.

Thanks,
Bryan Rasmussen

**Comment by soldair** [comment]
i decided to add support for mixed types in the default comparator. ill bump the major version just in case as it might break folks.

**Comment by soldair** [comment]
published as version v1.0.0 added test in test/strings.js
