### ISSUE TITLE
Update README for bs.insert

### ISSUE THREAD

**Issue by pheyvaer** [soldair/node-binarysearch#7]
Hi,
Great work with the library. I wanted to use a custom comparator for the `insert` function. In the code I saw that it was possible. However, this is not reflected in the documentation. Maybe you should add it? As it is a nice feature of the library. :smile:

**Comment by soldair** [comment]
i would love to merge a pull request for this. please go ahead if you have a moment =)

**Comment by soldair** [comment]
i mean i guess it it mentioned in examples but i should have a top level index with all of the api methods eh?

**Comment by pheyvaer** [comment]
Aight, will have a look at it :smile:

**Comment by soldair** [comment]
i think i merged the docs fixes you sent. thanks!
